from Room import *

depart=Menu("1ère année")
defiVoyance=CodeName("CodeName")
defiOneShot=Sphinx("Sphinx")
defiLunettes=Morpion("Morpion")
defiDoubleCoup=Integrale("Integrale")

trioInfernal=FightRoom(["Petit","Barcelo", "Torinesi"])
barcelo=FightRoom(["Barcelo"])
oliv=FightRoom(["Torinesi"])
petit=FightRoom(["Petit"])
bigMaths=FightRoom(["Petit","Barcelo"])
salletranquille=Room("Salle tranquille")
mecaSol=FightRoom(["Deschamps"])
thermo=FightRoom(["Nathalie Dias"])
communs=FightRoom(["Petit","Barcelo", "Torinesi"])
conseil=Conseil()

depart.SetVoisins(est = trioInfernal)
trioInfernal.SetVoisins(est = barcelo)
barcelo.SetVoisins(est = defiVoyance, sud = oliv)
oliv.SetVoisins(ouest = petit, sud = bigMaths, passage=salletranquille)
petit.SetVoisins(ouest = defiOneShot, est = oliv)
defiOneShot.SetVoisins(est=petit)
bigMaths.SetVoisins(sud = salletranquille)
salletranquille.SetVoisins(ouest = mecaSol)
mecaSol.SetVoisins(nord = thermo, sud = defiDoubleCoup, passage = conseil)
defiDoubleCoup.SetVoisins(nord = mecaSol)
thermo.SetVoisin(est = communs)
communs.SetVoisins(nord = defiLunettes, sud = conseil)
